name: my_game
description: My new Flame game
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.8.0

dependencies:
  audioplayers: ^6.4.0
  bloc: ^9.0.0
  equatable: ^2.0.7
  flame: ^1.29.0
  flame_audio: ^2.11.6
  flame_behaviors: ^1.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  google_fonts: ^6.2.1
  intl: ^0.20.2
  nes_ui: ^0.25.0
  game_repository:
    path: packages/game_repository
  statistics_repository:
    path: packages/statistics_repository
  flame_tiled: ^3.0.5
  quiver: ^3.2.2

dev_dependencies:
  bloc_test: ^10.0.0
  flame_test: ^1.19.2
  flutter_test:
    sdk: flutter
  mockingjay: ^2.0.0
  mocktail: ^1.0.4
  very_good_analysis: ^9.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/audio/
    - assets/images/unicorn_animation.png
    - assets/images/ant_walk.png
    - assets/images/modern_office/
    - assets/images/characters/
    - assets/licenses/poppins/
    - assets/tiles/
