name: statistics_repository
description: My new Dart package
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.8.0

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.26.2
  very_good_analysis: ^9.0.0
dependencies:
  equatable: ^2.0.7
